version: '3.7'
services:
  chromedriver:
    image: blueimp/chromedriver
    tmpfs: /tmp
    environment:
      - ENABLE_VNC=true
      - EXPOSE_X11=true
    volumes:
      - ./docker/assets:/home/webdriver/assets:ro
    ports:
      - 127.0.0.1:5900:5900
  app:
    build: ./docker/app/
    volumes:
      - ./:/var/www/application
    command: apache2-foreground
    ports:
      - 127.0.0.1:8080:80
